beejoo/beejoo/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from sonic_beejoo.views import design_type, category, color, add_goods, goods, good, add_to_cart, basket


urlpatterns = [
    url(r'^$', goods, name='index'),
    url(r'^admin/', admin.site.urls),
    url(r'^good/(?P<product_id>[0-9]+)/', good, name='good'),
    url(r'^addtocart/', add_to_cart, name='add_to_cart'),
    url(r'^basket/', basket, name='basket'),
    url(r'^design/', design_type, name='create_des'),
    url(r'^category/', category, name='create_cat'),
    url(r'^color/', color, name='create_col'),
    url(r'^add/', add_goods, name='add_good'),
    url(r'^users/', include('sb_auth.urls', namespace='sb_auth')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

beejoo/sb_auth/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url

from django.contrib.auth.views import login, logout_then_login
from django.views.generic import CreateView

from sb_auth.forms import CustomUserCreation

urlpatterns = [
    url(r'^login/', login, {
        'template_name': 'sb_auth/login.html'
    }, name='login'),
    url(r'^logout/', logout_then_login, name='logout'),
    url(r'^register/', CreateView.as_view(
        template_name='sb_auth/register.html',
        form_class=CustomUserCreation,
        success_url='/'
    ), name='register')
]

beejoo/sb_auth/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class CustomUser(AbstractUser):
    note = models.CharField(max_length=100, blank=True)

beejoo/sonic_beejoo/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.utils import timezone

# Create your models here.
class DesignType(models.Model):
    #камни, глина, бисер...
    name = models.CharField('Тип изделия', max_length=50, blank=False, unique=True)
    is_displayed = models.BooleanField('Отображать', default=True)

    class Meta:
        verbose_name_plural = 'Состав'

    def __str__(self):
        return self.name


class Category(models.Model):
    #браслет, серьги...
    name = models.CharField(max_length=30, blank=False, unique=True)
    is_displayed = models.BooleanField(default=True)

    class Meta:
        verbose_name_plural = 'Категория'

    def __str__(self):
        return self.name


class Color(models.Model):
    name = models.CharField(max_length=20, blank=False, unique=True)
    is_displayed = models.BooleanField(default=True)

    class Meta:
        verbose_name_plural = 'Цвет'

    def __str__(self):
        return self.name


class Good(models.Model):
    category = models.ForeignKey('Category')
    design_types = models.ManyToManyField('DesignType')
    colors = models.ManyToManyField('Color',related_name='all_colors')
    title = models.CharField(max_length=50, blank=False)
    short_description = models.CharField(max_length=100)
    full_description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    sale = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    img_uri = models.ImageField(upload_to='goods_img', blank=True)
    img_second_uri = models.ImageField(upload_to='goods_img', blank=True)
    data_created = models.DateTimeField(default=timezone.now())
    amount = models.IntegerField(default=1)
    slug = models.SlugField(max_length=50, blank=False, unique=True)
    is_displayed = models.BooleanField(default=True)

    class Meta:
        verbose_name_plural = 'Товар'


class Order(models.Model):
    good_id = models.ForeignKey('Good')
    quantity = models.IntegerField()
    total_sum = models.IntegerField()
    is_done = models.BooleanField(default=False)

    class Meta:
        verbose_name_plural = 'Заказ'

beejoo/sb_auth/forms.py
# -*- coding: utf-8 -*-
from django.contrib.auth.forms import UserCreationForm
from sb_auth.models import CustomUser

__author__ = 'gia_sebua'

class CustomUserCreation(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = ('username',)

beejoo/sonic_beejoo/forms.py
from django import forms
from django.core.exceptions import ValidationError

from sonic_beejoo.models import DesignType, Good, Category, Color


class DesignTypeForm(forms.ModelForm):
    class Meta:
        model = DesignType
        fields = '__all__'


class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = '__all__'


class ColorForm(forms.ModelForm):
    class Meta:
        model = Color
        fields = "__all__"

class GoodForm(forms.ModelForm):
    class Meta:
        model = Good
        fields = [ 'category',
                   'design_types',
                   'colors',
                   'title',
                   'short_description',
                   'price',
                   'amount',
                   'img_uri'
        ]

beejoo/sb_auth/views.py
from django.shortcuts import render

# Create your views here.
def register(request):
    raise NotImplemented('Please, extend me!')

beejoo/sonic_beejoo/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse, JsonResponse
from sonic_beejoo.forms import GoodForm, DesignTypeForm, CategoryForm, ColorForm
from sonic_beejoo.models import DesignType, Category, Color, Good


# Create your views here.
def design_type(request):
    if request.method == 'GET':
        des = DesignType.objects.all().filter(is_displayed=True)
        form = DesignTypeForm()
        c = {'designs': des, 'form': form}
        return render(request,'sonic_beejoo/attributes.html', c)
    elif request.method == 'POST':
        des = DesignType.objects.all()
        form = DesignTypeForm(request.POST)
        c = {'designs': des, 'form': form}
        if form.is_valid():
            form.save()
        return render(request,'sonic_beejoo/attributes.html', c)
    return HttpResponse(status=405)

def category(request):
    if request.method == 'GET':
        des = Category.objects.all().filter(is_displayed=True)
        form = CategoryForm()
        c = {'designs': des, 'form': form}
        return render(request,'sonic_beejoo/attributes.html', c)
    elif request.method == 'POST':
        des = Category.objects.all()
        form = CategoryForm(request.POST)
        c = {'designs': des, 'form': form}
        if form.is_valid():
            form.save()
        return render(request,'sonic_beejoo/attributes.html', c)
    return HttpResponse(status=405)


def color(request):
    if request.method == 'GET':
        des = Color.objects.all().filter(is_displayed=True)
        form = ColorForm()
        c = {'designs': des, 'form': form}
        return render(request,'sonic_beejoo/attributes.html', c)
    elif request.method == 'POST':
        des = Color.objects.all()
        form = ColorForm(request.POST)
        c = {'designs': des, 'form': form}
        if form.is_valid():
            form.save()
        return render(request,'sonic_beejoo/attributes.html', c)
    return HttpResponse(status=405)


def add_goods(request):
    if request.method == 'GET':
        form = GoodForm()
        return render(request, 'sonic_beejoo/goods.html', {'form': form})
    if request.method == 'POST':
        form = GoodForm(request.POST)
        if form.is_valid():
            form.save()
        return render(request, 'sonic_beejoo/goods.html', {'form': form})
    return HttpResponse(status=405)


def goods(request):
    if request.method == 'GET':
        in_basket = str(len(request.session['inbasket'])) if 'inbasket' in request.session else 0
        # visible_goods = Good.objects.all().select_related().prefetch_related(
        #     'colors', 'design_types', 'category'
        # ).first()
        visible_goods = Good.objects.all()
        return render(request, 'sonic_beejoo/product.html', {'goods': visible_goods, 'inbasket': in_basket})
    return HttpResponse(status=405)


def good(request, product_id):
    if request.method == 'GET':
        in_basket = str(len(request.session['inbasket'])) if 'inbasket' in request.session else 0
        return render(request, 'sonic_beejoo/good.html', {'goood': Good.objects.get(id=product_id), 'inbasket': in_basket})
    return HttpResponse(status=405)


def add_to_cart(request):
    if request.method == 'POST':
        if 'inbasket' not in request.session:
            request.session['inbasket'] = []
        request.session['inbasket'] += [request.POST['product']]
        return JsonResponse({'items_in_basket': str(len(request.session['inbasket']))})
    else:
        return redirect('/')


def basket(request):
    pass

beejoo/sb_auth/templates/sb_auth/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

<h1>Представтесь пожалуйста</h1>

<form action="{% url 'sb_auth:login' %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit">
</form>

</body>
</html>

beejoo/sb_auth/templates/sb_auth/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

<h1>Регистрация</h1>

<form action="{% url 'sb_auth:register' %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit">
</form>

</body>
</html>

beejoo/sonic_beejoo/templates/sonic_beejoo/_base.html
{% load static from staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block style %}{% endblock %}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <title>{% block title %}{% endblock %}</title>
<!--<style>body { padding-top: 70px; }</style> -->
</head>
<body >
<nav class="navbar navbar-inverse navbar-top">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <a class="navbar-brand" href="#">
          <img alt="Brand" src="/media/logo.png" width="50" height="50">
      </a>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="navbar">
      <ul class="nav navbar-nav">
        <li><a href="#">Главная</a></li>
        <li><a href="#">Каталог</a></li>
        <li><a href="#">Контакты</a></li>
        <li><a href="#">Оплата</a></li>
        <li><a href="#">Доставка</a></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
<div>
<h1>Sonic Beejoo Shop</h1>
в корзине <a href="#"><span class="basketText">{{ inbasket }}</span></a> товара

    {% block content %}
    {% endblock %}
</div>
<script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
<script src="{% static 'js/common.js' %}"></script>
</body>
</html>

beejoo/sonic_beejoo/templates/sonic_beejoo/attributes.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>hello</h1>

<form action="{% url 'create_des' %}" method="POST">
    {% csrf_token %}
    <h2>Design</h2>
    {{ form }}
    <input type="submit" value="Submit" />
</form>
<ul>
{% for design in designs %}
    <li>{{ design.name }}</li>
{% endfor %}
</ul>

<form action="{% url 'create_cat' %}" method="POST">
    {% csrf_token %}
    <h2>Cat</h2>
    {{ form }}
    <input type="submit" value="Submit" />
</form>
<ul>
{% for design in designs %}
    <li>{{ design.name }}</li>
{% endfor %}
</ul>

<form action="{% url 'create_col' %}" method="POST">
    {% csrf_token %}
    <h2>Color</h2>
    {{ form }}
    <input type="submit" value="Submit" />
</form>
<ul>
{% for design in designs %}
    <li>{{ design.name }}</li>
{% endfor %}
</ul>

</body>
</html>

beejoo/sonic_beejoo/templates/sonic_beejoo/good.html
{% extends "sonic_beejoo/_base.html" %}
{% block content %}
    <br>
    <div class="container">
            <img class="img-rounded" src="{{ goood.img_uri.url }}" width="300" height="300">
            <div class="col-md-3">
                <h2>{{ goood.title }}</h2>
                {{ goood.full_description }}<br>
                <p>Цена:{{ goood.price }} руб</p>
                <h4>Цвета:</h4>
                {% for color in goood.colors.all %}
                {{ color}}<br>
                {% endfor %}
                <h4>Состав:</h4>
                {% for des in goood.design_types.all %}
                {{ des}}<br>
                {% endfor %}
                <a href="javascript:history.go(-1)" class="btn btn-default btn-xs">Назад</a>
            </div>
    </div>
{% endblock %}

beejoo/sonic_beejoo/templates/sonic_beejoo/goods.html
{% extends "sonic_beejoo/_base.html" %}
{% block content %}
<div class="container">
<h1>Add</h1>
<form action="{% url 'add_good' %}" method="POST">
    <div class="form-group">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit" />
    </div>
</form>
</div>
{% endblock %}

beejoo/sonic_beejoo/templates/sonic_beejoo/product.html
{% extends "sonic_beejoo/_base.html" %}
{% block content %}
{% csrf_token %}
<div class="container">
{% for good in goods %}
    <div class="col-md-2">
    <h3><a href="{% url 'good' good.id %}">{{ good.title }}</a></h3><br>
    <img class="img-circle" src="{{ good.img_uri.url }}" width="150" height="150">
    <h4>Цвета:</h4>
    {% for color in good.colors.all %}
         {{ color}}<br>
    {% endfor %}
    <h4>Состав:</h4>
    {% for des in good.design_types.all %}
         {{ des}}<br>
    {% endfor %}
    <h4>Цена: {{ good.price }} руб.</h4>
        <button data-id="{{ good.pk }}" class="btn btn-default">Добавить в корзину</button>
    </div>
{% endfor %}
</div>
{% endblock %}